language: rust
rust:
  - stable

services:
  - docker

before_script:
  - export PATH="$PATH:$HOME/.cargo/bin"

script:
  - cargo test --release
  - echo "Running Autobahn TestSuite for client" && ./scripts/autobahn-client.sh
  - echo "Running Autobahn TestSuite for server" && ./scripts/autobahn-server.sh
